image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm start & npm run lint && npm run test && kill %1  # скрипт тестирования
